-- Software Deployment  
-- Task: Project     	


CREATE DATABASE IF NOT EXISTS `dvd_titles` 
 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

--
-- table structure
--

CREATE TABLE IF NOT EXISTS `dvd_titles`.`movies` (
	`ID` int(4) AUTO_INCREMENT PRIMARY KEY, 
	`Title` varchar(82) 
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

--
-- data dump
--

INSERT INTO `dvd_titles`.`movies` (`Title`) VALUES
 ('10'),
 ('12 Monkeys (DTS)'),
 ('12 Monkeys: Collector\'s Edition'),
 ('187: Special Edition'),
 ('1941: Collector\'s Edition'),
 ('200 Cigarettes'),
 ('2001: A Space Odyssey (Original Release)'),
 ('2001: A Space Odyssey (Repackaged Version)'),
 ('2010: The year We Made Contact'),
 ('3 Days Of The Condor'),
 ('48 HRS.'),
 ('8 Seconds'),
 ('9 1/2 Weeks'),
 ('Above The Law'),
 ('Absolute Power'),
 ('Ace Ventura: Pet Detective'),
 ('Ace Ventura: When Nature Calls'),
 ('Action Jackson'),
 ('Action Pack Gift Set'),
 ('Adam Sandler Collection'),
 ('Adam\'s Rib'),
 ('Addams Family'),
 ('Addams Family Values'),
 ('Addicted to Love'),
 ('Adventures Of Pinocchio'),
 ('Adventures Of Priscilla, Queen Of The Desert (MGM/UA)'),
 ('Adventures Of Sebastian Cole'),
 ('Affliction'),
 ('Al Pacino Collection'),
 ('Alanis Morissette: Jagged Little Pill, Live'),
 ('Alfred Hitchcock Collection (Box Set)'),
 ('All Dogs Christmas Carol'),
 ('All Quiet On The Western Front (1930)'),
 ('All The President\'s Men'),
 ('Altered States'),
 ('Always'),
 ('Amadeus'),
 ('American Flyers'),
 ('American Gigolo'),
 ('American Graffiti: Collector\'s Edition'),
 ('American History X: Platinum Edition'),
 ('American in Paris (MGM/UA)'),
 ('American In Paris (Warner)'),
 ('American Pie: Collector\'s Edition (R Rated Version)'),
 ('American Pie: Collector\'s Edition (Unrated Version)'),
 ('American President'),
 ('Analyze This'),
 ('Anchors Aweigh'),
 ('Annie Hall'),
 ('Another 48 Hours'),
 ('Apocalypse Now'),
 ('Apollo 13 (DTS)'),
 ('Apollo 13: Collector\'s Edition'),
 ('Apostle: Collector\'s Edition'),
 ('Army Of Darkness'),
 ('Art Garfunkel: Across America'),
 ('Arthur'),
 ('Assassins'),
 ('Astronaut\'s Wife, The'),
 ('At First Sight'),
 ('Austin Powers: Platinum Edition'),
 ('Austin Powers: The Spy Who Shagged Me: Platinum Edition'),
 ('Avengers: The Movie'),
 ('Babe (DTS)'),
 ('Babe: Pig In The City'),
 ('Bachelor'),
 ('Back To School'),
 ('Backdraft'),
 ('Badlands'),
 ('Barbarella'),
 ('Barefoot In The Park'),
 ('Barry Lyndon'),
 ('Baseball'),
 ('BASEketball'),
 ('Bataan'),
 ('Batman'),
 ('Batman & Robin'),
 ('Batman Beyond: The Movie'),
 ('Batman Forever'),
 ('Batman Returns'),
 ('Batman: Mask Of The Phantasm'),
 ('Batteries Not Included'),
 ('Battlestar Galactica'),
 ('Beavis And Butt-Head Do America'),
 ('Bed Of Roses'),
 ('Beethoven'),
 ('Beethoven\'s 2nd'),
 ('Beetlejuice'),
 ('Before Sunrise'),
 ('Beguiled'),
 ('Ben-Hur'),
 ('Besieged: Platinum Edition'),
 ('Best Bits Of Mr. Bean (Universal)'),
 ('Best Man'),
 ('Betrayed'),
 ('Betsy'),
 ('Big Bully'),
 ('Big Red One'),
 ('Big Sleep'),
 ('Billy Madison'),
 ('Bird On A Wire'),
 ('Birdcage'),
 ('Birds: Collector\'s Edition'),
 ('Bjork: All Is Full Of Love'),
 ('Bjork: Volumen'),
 ('Black Beauty (1994)'),
 ('Black Dog'),
 ('Black Rain (1989)'),
 ('Black Stallion'),
 ('Blade Runner: Director\'s Cut'),
 ('Blade: Platinum Edition'),
 ('Blast From The Past'),
 ('Blazing Saddles'),
 ('Blood, Guts, Bullets And Octane'),
 ('Blown Away'),
 ('Blue Hawaii'),
 ('Blue Velvet (MGM/UA)'),
 ('Blues Brothers 2000 (DTS)'),
 ('Blues Brothers 2000: Collector\'s Edition'),
 ('Blues Brothers: Collector\'s Edition'),
 ('Body Heat (1981)'),
 ('Body Snatchers'),
 ('Bodyguard'),
 ('Boiling Point (1993)'),
 ('Bone Collector: Collector\'s Edition'),
 ('Bonfire Of The Vanities'),
 ('Bonnie And Clyde (Original Version)'),
 ('Bonnie And Clyde (Remastered Version)'),
 ('Boogie Nights: Platinum Edition'),
 ('Born On The Fourth Of July'),
 ('Born On The Fourth Of July (DTS)'),
 ('Bound For Glory'),
 ('Bowfinger'),
 ('Boxer (DTS)'),
 ('Boxer: Collector\'s Edition'),
 ('Boys On The Side'),
 ('Brainstorm'),
 ('Brazil'),
 ('Breakdown'),
 ('Breakfast At Tiffany\'s'),
 ('Breakfast Club'),
 ('Breathless'),
 ('Bride Of Chucky'),
 ('Bride Of Frankenstein: Classic Monster Collection'),
 ('Bridge At Remagen'),
 ('Bridge Too Far'),
 ('Bridges Of Madison County'),
 ('Brigadoon (MGM/UA)'),
 ('Brigadoon (Warner)'),
 ('Bringing Out The Dead'),
 ('Buffalo 66'),
 ('Bulletproof'),
 ('Bullitt'),
 ('Burbs'),
 ('Burglar'),
 ('Burn The Floor'),
 ('Cabaret: Special Edition'),
 ('Caddyshack'),
 ('Caddyshack 2'),
 ('Caddyshack: Special Edition'),
 ('Camelot: Special Edition'),
 ('Campus Comedy Classics: Collector\'s Edition'),
 ('Candidate'),
 ('Cannonball Run 2'),
 ('Career Opportunities'),
 ('Carlito\'s Way'),
 ('Carnal Knowledge (MGM/UA)'),
 ('Carrie'),
 ('Casablanca: Special Edition'),
 ('Casablanca: Special Edition (Warner)'),
 ('Casino'),
 ('Cat On A Hot Tin Roof (1958)'),
 ('Cat On A Hot Tin Roof (Warner)'),
 ('Cats (Universal)'),
 ('Chamber'),
 ('Chariots Of Fire'),
 ('Child\'s Play'),
 ('Child\'s Play 2: Chucky\'s Back'),
 ('Chill Factor: Special Edition'),
 ('Chinatown'),
 ('Chitty Chitty Bang Bang'),
 ('Christmas Story (MGM/UA)'),
 ('Christmas Story (Warner)'),
 ('Circuit 1:1'),
 ('Circuit 1:2'),
 ('Circuit 1:3'),
 ('Circuit 1:4'),
 ('Circuit 1:5'),
 ('Circuit 6'),
 ('City Hall'),
 ('City Of Angels: Special Edition'),
 ('Clan Of The Cave Bear'),
 ('Classic Steve Martin'),
 ('Clean And Sober'),
 ('Clear And Present Danger'),
 ('Cleopatra Jones'),
 ('Client'),
 ('Clockers'),
 ('Clockwork Orange'),
 ('Clue'),
 ('Clueless'),
 ('CNN Millennium 2000: Incredible Moments From The Celebration'),
 ('Cobra (1986)'),
 ('Color Purple'),
 ('Coma'),
 ('Coming To America'),
 ('Conan The Barbarian'),
 ('Conan The Barbarian: Collector\'s Edtion'),
 ('Conan The Destroyer'),
 ('Congo'),
 ('Conspiracy Theory'),
 ('Contact: Special Edition'),
 ('Cool Hand Luke'),
 ('Cooley High'),
 ('Cop & A Half'),
 ('Copycat: Special Edition'),
 ('Corrina, Corrina'),
 ('Corruptor'),
 ('Court Jester'),
 ('Cowboy Way'),
 ('Cowboys'),
 ('Crash'),
 ('CreepShow'),
 ('Crooklyn'),
 ('Crush'),
 ('Cry Freedom'),
 ('Cry In The Dark'),
 ('Cyborg'),
 ('Damage'),
 ('Dangerous Beauty'),
 ('Dangerous Ground'),
 ('Dangerous Liaisons'),
 ('Dante\'s Peak (DTS)'),
 ('Dante\'s Peak: Collector\'s Edition'),
 ('Dark City: Platinum Edition'),
 ('Dark Half'),
 ('Dark Victory'),
 ('Darkman'),
 ('Darkman 2: The Return Of Durant'),
 ('Dave'),
 ('Day of The Jackal'),
 ('Daylight (DTS)'),
 ('Daylight: Collector\'s Edition'),
 ('Days Of Heaven'),
 ('Days Of Thunder'),
 ('Dazed & Confused'),
 ('Dead Again: Special Edition'),
 ('Dead Bang'),
 ('Dead Calm'),
 ('Dead Man On Campus'),
 ('Dead Man Walking'),
 ('Dead Men Don\'t Wear Plaid'),
 ('Death Becomes Her'),
 ('Deathtrap'),
 ('Deconstructing Harry'),
 ('Deep Blue Sea: Special Edition'),
 ('Deep Cover'),
 ('Deep Impact'),
 ('Deer Hunter'),
 ('Deliverance'),
 ('Demolition Man: Special Edition'),
 ('Depeche Mode: The Videos \'86-\'98'),
 ('Desperately Seeking Susan: Special Edition'),
 ('Detroit Rock City: Platinum Edition'),
 ('Devil\'s Advocate: Special Edition (New Release)'),
 ('Devil\'s Advocate: Special Edition (Original Release)'),
 ('Diggstown'),
 ('Diner'),
 ('Dinner Game'),
 ('Dirty Dozen'),
 ('Dirty Dozen (Warner)'),
 ('Dirty Harry'),
 ('Dirty Work'),
 ('Disclosure'),
 ('Disturbing Behavior: Special Edition'),
 ('Divine Madness'),
 ('Do The Right Thing'),
 ('Doc Hollywood'),
 ('Doctor Zhivago'),
 ('Dog Day Afternoon'),
 ('Dolores Claiborne: Special Edition'),
 ('Don Juan de Marco'),
 ('Doors: Collector\'s Edition'),
 ('Double Jeopardy'),
 ('Dr. No'),
 ('Dr. No: Special Edition'),
 ('Dracula: Classic Monster Collection'),
 ('Dragnet'),
 ('Dragon: The Bruce Lee Story: Collector\'s Edition'),
 ('Dragonheart (DTS)'),
 ('Dragonheart: Collector\'s Edition'),
 ('Driving Miss Daisy'),
 ('Drop Dead Gorgeous'),
 ('Drop Squad'),
 ('Drop Zone'),
 ('Dudley Do Right'),
 ('Dumb & Dumber'),
 ('Dune'),
 ('DVD F/X Gift Set'),
 ('Ed-TV (DTS)'),
 ('Ed-TV: Collector\'s Edition'),
 ('Eiger Sanction'),
 ('El Dorado'),
 ('Election'),
 ('Elvis \'56'),
 ('Elvis Presley: Aloha From Hawaii'),
 ('Elvis Presley: The Alternate Aloha Concert'),
 ('Embrace Of The Vampire'),
 ('End Of Days: Collector\'s Edition'),
 ('End Of Violence'),
 ('Enter The Dragon: Special Edition'),
 ('Eraser'),
 ('Eric Clapton & Friends: In Concert: The Crossroads Benefit'),
 ('Eric Clapton Unplugged'),
 ('Eric Clapton: 24 Nights'),
 ('Eric Clapton: Clapton Chronicles: The Best Of Eric Clapton'),
 ('Escape From Alcatraz'),
 ('Escape From L.A.'),
 ('Event Horizon'),
 ('Excalibur'),
 ('Executive Decision'),
 ('Exorcist, The'),
 ('Exorcist 3'),
 ('Exorcist: 25th Anniversary Special Edition'),
 ('Extreme Adventures Of Super Dave'),
 ('Extreme DVD Gift Set'),
 ('Extreme Measures'),
 ('Eye Of The Needle'),
 ('Eyes Wide Shut'),
 ('F/X'),
 ('F/X 2'),
 ('Face/Off'),
 ('Fair Game'),
 ('Falcon & The Snowman'),
 ('Fallen'),
 ('Falling Down'),
 ('Far And Away'),
 ('Fast Times At Ridgemont High: Collector\'s Edition'),
 ('Father\'s Day'),
 ('Fear (1998)'),
 ('Fear And Loathing In Las Vegas'),
 ('Fearless'),
 ('Feeling Minnesota'),
 ('Ferris Bueller\'s Day Off'),
 ('Fiddler on The Roof: Special Edition'),
 ('Field of Dreams: Collector\'s Edition'),
 ('Fierce Creatures'),
 ('Filter: Title Of DVD'),
 ('Final Analysis'),
 ('Fire Down Below'),
 ('Firm'),
 ('First Deadly Sin'),
 ('First Wives Club'),
 ('Fish Called Wanda'),
 ('Fistful Of Dollars'),
 ('Five Corners (Universal)'),
 ('Flawless'),
 ('Fled'),
 ('Fleetwood Mac: The Dance'),
 ('Fletch'),
 ('Flintstones (DTS)'),
 ('Flintstones: Collector\'s Edition'),
 ('For a Few Dollars More'),
 ('For Love Of The Game'),
 ('For Richer or Poorer'),
 ('For Richer Or Poorer (DTS)'),
 ('For Whom The Bell Tolls'),
 ('For Your Eyes Only: Special Edition'),
 ('Forbidden Planet (MGM/UA)'),
 ('Forbidden Planet (Warner)'),
 ('Force 10 From Navarone'),
 ('Forever Young'),
 ('Forget Paris'),
 ('Four Weddings and a Funeral (MGM/UA)'),
 ('Frank Sinatra: A Man & His Music + Ella + Jobim'),
 ('Frank Sinatra: A Man & His Music Volume 1'),
 ('Frank Sinatra: A Man And His Music Volume 2'),
 ('Frank Sinatra: Francis Albert Sinatra Does His Thing'),
 ('Frank Sinatra: Ol\' Blue Eyes Is Back'),
 ('Frank Sinatra: Sinatra'),
 ('Frank Sinatra: Sinatra In Concert At Royal Festival Hall'),
 ('Frank Sinatra: The Main Event'),
 ('Frank Sinatra: The Man And His Music With The Count Basie Orchestra'),
 ('Frankenstein: Classic Monster Collection'),
 ('Frantic'),
 ('Free Willy'),
 ('Freejack'),
 ('Friday'),
 ('Friday The 13th'),
 ('Friday The 13th: Part 2'),
 ('Fried Green Tomatoes: Collector\'s Edition'),
 ('Friends And Lovers'),
 ('Frighteners'),
 ('From Russia with Love'),
 ('Fugitive'),
 ('Full Force DVD Gift Set'),
 ('Full Metal Jacket'),
 ('Funny Farm'),
 ('Funny Thing Happened On The Way To The Forum'),
 ('G.I. Blues'),
 ('Galaxy Quest'),
 ('Galaxy Quest (DTS)'),
 ('Gallipoli'),
 ('Gauntlet'),
 ('General\'s Daughter'),
 ('George Balanchine\'s Nutcracker'),
 ('Get Real'),
 ('Get Shorty'),
 ('Getaway (1972)'),
 ('Getaway (1994)'),
 ('Ghost And The Darkness'),
 ('Ghosts Of Mississippi'),
 ('Gigi (MGM/UA)'),
 ('Gigi (Warner)'),
 ('Glimmer Man'),
 ('Gods And Monsters: Collector\'s Edition'),
 ('Going My Way / Holiday Inn'),
 ('Golden Child'),
 ('GoldenEye'),
 ('Goldeneye: Special Edition'),
 ('Goldfinger'),
 ('Goldfinger: Special Edition'),
 ('Gone With The Wind (MGM/UA)'),
 ('Gone With The Wind (Warner)'),
 ('Good, The Bad & The Ugly'),
 ('Goodbye Girl'),
 ('Goodbye Lover'),
 ('GoodFellas'),
 ('Gorillas In The Mist'),
 ('Grace Of My Heart: Collector\'s Edition'),
 ('Graduate: Special Edition (MGM/UA)'),
 ('Great Escape'),
 ('Great Outdoors'),
 ('Great Santini'),
 ('Great Train Robbery'),
 ('Greedy'),
 ('Green Berets'),
 ('Green Mile'),
 ('Gremlins (Discontinued)'),
 ('Grumpier Old Men'),
 ('Grumpy Old Men'),
 ('Guilty By Suspicion'),
 ('Guys & Dolls'),
 ('Gypsy (Warner)'),
 ('Hackers'),
 ('Hair'),
 ('Half Baked'),
 ('Hang \'Em High'),
 ('Happy Gilmore'),
 ('Hard Rain'),
 ('Hard Target'),
 ('Hard to Kill'),
 ('Hard Way'),
 ('Harold And Maude'),
 ('Havana'),
 ('Heart And Souls'),
 ('Heat (1995)'),
 ('Heaven Can Wait'),
 ('Heaven\'s Gate'),
 ('Hellfighters'),
 ('Henry & June'),
 ('Her Alibi'),
 ('Hercules & Xena: Animated Movie'),
 ('Hercules Action Pack'),
 ('Hercules: Lost Kingdom/ Amazon Women'),
 ('Hercules: Warrior Princess/ Gauntlet/ Unchained Heart'),
 ('Hidden: Platinum Edition'),
 ('High Plains Drifter'),
 ('Hindenburg'),
 ('Holcroft Covenant: Special Edition'),
 ('Hollywood Confidential'),
 ('Home Fries'),
 ('Honeymoon In Vegas (MGM/UA)'),
 ('Hoodlum'),
 ('Hooper'),
 ('Hoosiers (MGM/UA)'),
 ('Hootie And The Blowfish: A Series Of Short Trips'),
 ('Hot Spot'),
 ('House On Haunted Hill: Special Edition'),
 ('House On The Haunted Hill'),
 ('House Party'),
 ('House Party 2'),
 ('House Party 3'),
 ('Housesitter'),
 ('How The Grinch Stole Christmas / Horton Hears A Who (MGM/UA)'),
 ('How The Grinch Stole Christmas / Horton Hears A Who (Warner)'),
 ('How The West Was Won'),
 ('How To Make An American Quilt'),
 ('How To Stuff A Wild Bikini'),
 ('How To Succeed In Business Without Really Trying'),
 ('Hudsucker Proxy'),
 ('Hunchback Of Notre Dame (Warner / 1939)'),
 ('Hunt For Red October'),
 ('Hunted'),
 ('Hurlyburly: Platinum Edition'),
 ('I Married A Strange Person'),
 ('Idolmaker'),
 ('Imagine: John Lennon'),
 ('In & Out'),
 ('In Country'),
 ('In Love And War'),
 ('In The Mouth Of Madness: Platinum Edition'),
 ('In The Name Of The Father'),
 ('Incognito'),
 ('Innocent Blood'),
 ('Internal Affairs'),
 ('Interview With The Vampire'),
 ('Interview With The Vampire: Special Edition'),
 ('Invasion Of The Body Snatchers (1978)'),
 ('Iron Giant'),
 ('Island Of Dr. Moreau: Director\'s Cut'),
 ('Jack Frost (1998)'),
 ('Jackal (DTS)'),
 ('Jackal: Collector\'s Edition'),
 ('Jackie Chan\'s First Strike'),
 ('Jade'),
 ('Jailhouse Rock'),
 ('James Bond Collection #1'),
 ('James Bond Collection #2'),
 ('Jason\'s Lyric (MGM/UA)'),
 ('Jaws: Collector\'s Edition'),
 ('Jaws: Collector\'s Edition (DTS)'),
 ('Jennifer 8'),
 ('Jeremiah Johnson'),
 ('Jerk'),
 ('Jesus Christ Superstar'),
 ('Jezebel'),
 ('JFK: Special Edition Director\'s Cut'),
 ('Jimi Hendrix'),
 ('Joe Kidd'),
 ('Joe\'s Apartment'),
 ('John Belushi Collection'),
 ('John Fogerty: Premonition'),
 ('Joseph & The Amazing Technicolor Dreamcoat'),
 ('Jungle Fever'),
 ('Junior'),
 ('Just Cause'),
 ('Just The Ticket'),
 ('K-9'),
 ('K-911'),
 ('Kelly\'s Heroes'),
 ('Key Largo'),
 ('Killer Elite'),
 ('Killer\'s Kiss'),
 ('Killing'),
 ('Killing Fields'),
 ('Kindergarten Cop'),
 ('King And I (1999)'),
 ('King Creole'),
 ('King Kong'),
 ('Kingpin: Special Edition'),
 ('Kiss The Girls'),
 ('Kiss The Sky'),
 ('Kissing A Fool'),
 ('Kull Conqueror'),
 ('L. A. Confidential: Special Edition'),
 ('La Cucaracha: Special Edition'),
 ('La Traviata'),
 ('Ladyhawke'),
 ('Land Before Time'),
 ('Last Boy Scout'),
 ('Last Man Standing'),
 ('Last Night'),
 ('Last Starfighter: Collector\'s Edition'),
 ('Last Tango In Paris'),
 ('Lawnmower Man: Platinum Edition'),
 ('Lean On Me'),
 ('Leave it to Beaver'),
 ('Leaving Las Vegas'),
 ('Led Zeppelin: The Song Remains The Same'),
 ('Lethal Weapon'),
 ('Lethal Weapon 2'),
 ('Lethal Weapon 2: Director\'s Cut'),
 ('Lethal Weapon 3'),
 ('Lethal Weapon 3: Director\'s Cut'),
 ('Lethal Weapon 4'),
 ('Lethal Weapon Gift Set'),
 ('Lethal Weapon: Director\'s Cut'),
 ('Leviathan'),
 ('Liar Liar'),
 ('Liar Liar (DTS)'),
 ('Liar, Liar: Collector\'s Edition'),
 ('License To Kill: Special Edition'),
 ('Life'),
 ('Lifeforce'),
 ('Lionheart'),
 ('Little Princess'),
 ('Little Rascals'),
 ('Little Rascals (DTS)'),
 ('Little Shop of Horrors: Special Edition (Original Version)'),
 ('Little Shop Of Horrors: Special Edition (Remastered Version)'),
 ('Live And Let Die: Special Edition'),
 ('Living Out Loud: Platinum Edition'),
 ('Local Hero'),
 ('Logan\'s Run: Special Edition'),
 ('Lolita'),
 ('Lone Star'),
 ('Lonely Guy'),
 ('Long Kiss Goodnight'),
 ('Lord Of Illusions: Special Edition'),
 ('Lost And Found'),
 ('Lost Boys'),
 ('Lost In Space: The Movie: Platinum Edition'),
 ('Love And Death On Long Island'),
 ('Love Jones'),
 ('Lovesick'),
 ('Mad City'),
 ('Mad Max Beyond Thunderdome'),
 ('Made In America'),
 ('Madigan'),
 ('Madonna: Ciao Italia: Live From Italy'),
 ('Madonna: The Girlie Show: Live Down Under'),
 ('Madonna: The Video Collection 1992-1999'),
 ('Magnificent Seven'),
 ('Major League 2'),
 ('Major League 3: Back To The Minors'),
 ('Major Payne'),
 ('Malcolm X'),
 ('Mallrats: Collector\'s Edition'),
 ('Maltese Falcon'),
 ('Barenaked Ladies: Too Little Too Late DVD Single'),
 ('Casino Lights \'99: Montreux Jazz Festival'),
 ('Dream Theater: Metropolis 2000: Scenes From New York (Special Edition)'),
 ('Static-X: Where The Hell Are We And What Day Is It: This Is Static-X'),
 ('Strauss: New Year\'s Concert 2001: Nikolaus Harnoncourt (DVD-Audio)'),
 ('Vivaldi: The Four Season'),
 ('Alice (1990)'),
 ('Another Woman'),
 ('Antitrust (Special Edition)'),
 ('Apartment'),
 ('Barefoot Contessa'),
 ('Beach Blanket Bingo'),
 ('Crimes And Misdemeanors'),
 ('Donovan\'s Brain'),
 ('Dr. Goldfoot And The Bikini Machine'),
 ('Entertainer'),
 ('Fall Of The House Of Usher (Special Edition/ 1960)'),
 ('Hope And Glory'),
 ('Kiss Me Deadly'),
 ('Madness Of King George'),
 ('Marty'),
 ('Misfits'),
 ('Moby Dick (1956)'),
 ('Pit And The Pendulum (Special Edition/ 1961)'),
 ('Platoon (Special Edition)'),
 ('Rembrandt'),
 ('Salvador (Special Edition)'),
 ('September'),
 ('Shadows And Fog'),
 ('Something Wild'),
 ('Sweet Smell Of Success'),
 ('Thing With Two Heads'),
 ('Tom Jones'),
 ('Village Of The Giants'),
 ('Woody Allen Collection 1987-1992'),
 ('X: The Man With The X-Ray Eyes (Special Edition)'),
 ('Gummo'),
 ('Julien Donkey Boy'),
 ('Bridges Of Toko-Ri'),
 ('Catch 22 (Special Edition)'),
 ('Donovan\'s Reef'),
 ('Hell Is For Heroes'),
 ('In Harm\'s Way'),
 ('Kill Shot'),
 ('Man Who Shot Liberty Valance'),
 ('Sons Of Katie Elder'),
 ('Star Trek TV #23: A Private Little War/ The Gamesters Of Triskelion'),
 ('Star Trek TV #24: Obsession/ The Immunity Syndrome'),
 ('Sunshine'),
 ('Uncommon Valor'),
 ('Jaws 2'),
 ('Fugitive (Special Edition)'),
 ('Serpent\'s Kiss'),
 ('What Women Want (Special Edition)'),
 ('Gormenghast'),
 ('Charlotte\'s Web'),
 ('Shadow Of The Vampire (Special Edition)'),
 ('Two Family House'),
 ('Blue Planet: IMAX'),
 ('Cartoon Crack-Ups'),
 ('Dream Is Alive: IMAX'),
 ('V: The Original Miniseries (Special Edition)'),
 ('2001: A Space Odyssey'),
 ('Barry Lyndon'),
 ('Before Night Falls (Special Edition)'),
 ('Best In Show'),
 ('Clockwork Orange'),
 ('Dungeons And Dragons (Special Edition)'),
 ('Full Metal Jacket'),
 ('Game Of Death (1978)'),
 ('Lolita'),
 ('Nutty Professor 2: The Klumps Uncensored (Special Edition)'),
 ('Pay It Forward (Special Edition)'),
 ('Playboy 2000: The Party Continues'),
 ('Playboy Centerfold: 2001 Playmate Of The Year'),
 ('Shining'),
 ('Stanley Kubrick Collection'),
 ('Star Trek TV #25: A Piece Of The Action/ By Any Other Name'),
 ('Star Trek TV #26: Return To Tomorrow/ Patterns Of Force'),
 ('X-Men: Reunion/ Out Of The Past/ No Mutant Is An Island'),
 ('X-Men: Sanctuary/ Proteus/ Weapon X, Lies And Videotape'),
 ('Eyes Wide Shut (ReRelease)'),
 ('Save The Last Dance (Special Edition)'),
 ('You Can Count On Me (Special Edition)'),
 ('Forever Mine'),
 ('Holiday Heart'),
 ('Bach: St. Matthew Passion: Harnoncourt (DVD-Audio)'),
 ('Chanticleer: Magnificat (DVD-Audio)'),
 ('Fleetwood Mac: Rumours (DVD-Audio)'),
 ('Messiaen: Vingt Regards Sur L\'Enfant Jesus: Aimard (DVD-Audio)'),
 ('All Revved Up'),
 ('Bagdad Cafe'),
 ('Black Robe'),
 ('Claim'),
 ('Cotton Club'),
 ('Cutter\'s Way'),
 ('Go Fish'),
 ('Hollywood Shuffle'),
 ('Hotel New Hampshire'),
 ('Liebestraum'),
 ('Marat Sade'),
 ('Theremin: An Electronic Odyssey'),
 ('Who\'ll Stop The Rain'),
 ('Chocolat'),
 ('La Cage Aux Folles'),
 ('La Cage Aux Folles II'),
 ('Madonna: What It Feels Like For A Girl DVD Single'),
 ('Apollo 13 (Special Edition/ Dolby Digital)/ Backdraft'),
 ('Casino/ Carlito\'s Way'),
 ('12 Monkeys (Special Edition/ Dolby Digital)/ Jackal'),
 ('Man In The Iron Mask (MGM/UA)'),
 ('Man On The Moon: Collector\'s Edition'),
 ('Man Who Knew Too Little'),
 ('Man Who Would be King'),
 ('Man With No Name: Clint Eastwood Gift Set'),
 ('Man With The Golden Gun: Special Edition'),
 ('Man With Two Brains'),
 ('Mana: MTV Unplugged'),
 ('Manchurian Candidate: Special Edition'),
 ('Marnie: Collector\'s Edition'),
 ('Married To The Mob'),
 ('Mars Attacks!'),
 ('Mask: Platinum Edition'),
 ('Matrix, The'),
 ('Maverick'),
 ('McKenzie Break'),
 ('Mean Streets'),
 ('Meet Joe Black'),
 ('Memphis Belle'),
 ('Menace II Society'),
 ('Mercury Rising'),
 ('Mercury Rising (DTS)'),
 ('Mercury Rising: Collector\'s Edition'),
 ('Message In A Bottle'),
 ('Metallica: A Year & A Half In The Life Of Metallica #1'),
 ('Metallica: Cliff \'Em All'),
 ('Metallica: Cunning Stunts'),
 ('Metallica: With The San Francisco Symphony: S&M'),
 ('Meteor'),
 ('Metroland'),
 ('Michael'),
 ('Michael Collins'),
 ('Michael Crawford In Concert'),
 ('Michael Flatley: Lord Of The Dance (Universal)'),
 ('Mickey Blue Eyes'),
 ('Midnight Cowboy'),
 ('Midnight In The Garden Of Good And Evil'),
 ('Miss Julie'),
 ('Missing In Action'),
 ('Mission Impossible'),
 ('Mister Roberts: Premiere Collection'),
 ('Mod Squad: The Movie'),
 ('Molly'),
 ('Money Talks'),
 ('Monkey Shines'),
 ('Monterey Jazz Festival: 40 Legendary Years'),
 ('Moonraker'),
 ('Moonraker: Special Edition'),
 ('Moonstruck: Special Edition'),
 ('More Treasures Of The Twilight Zone'),
 ('Mortal Kombat: Annilihation: Platinum Edition'),
 ('Mortal Kombat: The Movie'),
 ('Mosquito Coast'),
 ('Most Wanted'),
 ('Mother Night'),
 ('Mr. Death: The Rise And Fall Of Fred A. Leuchter Jr.'),
 ('Mr. Mom'),
 ('Mr. Mumble'),
 ('Mr. Nice Guy'),
 ('Mr. Wonderful'),
 ('Mummy: Classic Monster Collection (1932)'),
 ('Mummy: Collector\'s Edition (LBX)'),
 ('Mummy: Collector\'s Edition (1999 / P&S)'),
 ('Murder at 1600'),
 ('Murder In The First'),
 ('Music Man: Special Edition'),
 ('My Blue Heaven'),
 ('My Fair Lady: Premiere Collection'),
 ('My Fellow Americans'),
 ('My Giant'),
 ('My Sergei'),
 ('Mystery Men'),
 ('Mystery Train'),
 ('Natalie Merchant: Live In Concert'),
 ('National Geographic: 30 Years Of National Geographic Specials'),
 ('National Geographic: Nature\'s Fury'),
 ('National Geographic: Secrets Of The Titanic'),
 ('National Geographic: Surviving Everest'),
 ('National Geographic: The Battle For Midway'),
 ('National Geographic: The Photographers'),
 ('National Geographic: Tigers In The Snow'),
 ('National Lampoon\'s Animal House'),
 ('National Lampoon\'s Animal House: Collector\'s Edition'),
 ('National Lampoon\'s Christmas Vacation'),
 ('National Lampoon\'s Loaded Weapon'),
 ('National Lampoon\'s Vacation'),
 ('National Velvet'),
 ('Negotiator: Premiere Collection'),
 ('Neil Young: Silver And Gold'),
 ('Network (MGM/UA)'),
 ('Network (Warner)'),
 ('New Jack City'),
 ('Next Friday: Platinum Series'),
 ('Next Of Kin'),
 ('Nick Of Time'),
 ('Night At The Roxbury'),
 ('Night Falls On Manhattan: Special Edition'),
 ('Night Of The Hunter'),
 ('Night Shift'),
 ('Nightmare on Elm Street, A'),
 ('Nightmare On Elm Street Collection: Platinum Edition'),
 ('No Way Out'),
 ('Nothing But Trouble'),
 ('Notting Hill: Collector\'s Edition'),
 ('Now And Then'),
 ('Nutty Professor'),
 ('Nutty Professor (DTS)'),
 ('October Sky: Collector\'s Edition'),
 ('Odd Couple II'),
 ('Omega Man'),
 ('On Deadly Ground'),
 ('On Her Majesty\'s Secret Service: Special Edition'),
 ('On The Beach'),
 ('On The Town'),
 ('Once Upon A Time In America'),
 ('One Flew Over The Cuckoo\'s Nest'),
 ('One Man\'s Hero'),
 ('One Night Stand: Platinum Edition'),
 ('One True Thing'),
 ('Original Gangstas'),
 ('Othello (Warner)'),
 ('Out For Justice'),
 ('Out Of Africa: Collector\'s Edition'),
 ('Out Of Sight (DTS)'),
 ('Out Of Sight: Collector\'s Edition'),
 ('Out Of Towners'),
 ('Outbreak'),
 ('Outland'),
 ('Outlaw Josey Wales'),
 ('Outsiders'),
 ('Overboard'),
 ('Pacific Heights'),
 ('Package'),
 ('Pajama Game'),
 ('Pale Rider'),
 ('Palmetto'),
 ('Pantera: 3 Vulgar Videos From Hell'),
 ('Paper'),
 ('Papillon'),
 ('Parallax View'),
 ('Parenthood'),
 ('Passenger 57'),
 ('Patch Adams'),
 ('Patch Adams (DTS)'),
 ('Patch Adams: Collector\'s Edition'),
 ('Paths Of Glory'),
 ('Patriot Games'),
 ('Paul Simon: GraceLand: The African Concert'),
 ('Payback'),
 ('Pebble & The Penguin'),
 ('Pecker: Platinum Edition'),
 ('Pee-Wee\'s Big Adventure: Special Edition'),
 ('Pelican Brief'),
 ('Perfect Murder: Special Edition'),
 ('Phantasm: Special Edition'),
 ('Phantom'),
 ('Philadelphia Story (MGM/UA)'),
 ('Philadelphia Story (Warner)'),
 ('Pillow Talk'),
 ('Pink Panther'),
 ('Pink Panther Cartoon Collection: Jet Pink'),
 ('Pink Panther Strikes Again'),
 ('Player: Platinum Edition'),
 ('Players Club'),
 ('Pleasantville: Platinum Edition'),
 ('Point Of No Return'),
 ('Poison Ivy'),
 ('Poison Ivy 2: Lily'),
 ('Poison Ivy III: The New Seduction'),
 ('Pokemon: The First Movie: Special Edition'),
 ('Police Academy'),
 ('Poltergeist (MGM/UA)'),
 ('Poltergeist (Warner)'),
 ('Pork Chop Hill'),
 ('Postman'),
 ('Postman Always Rings Twice'),
 ('Power'),
 ('Power Of One'),
 ('Practical Magic: Special Edition'),
 ('Presidio'),
 ('Presumed Innocent'),
 ('Primal Fear'),
 ('Primary Colors'),
 ('Primary Colors (DTS)'),
 ('Prince: The Hits Collection'),
 ('Private Benjamin'),
 ('Private Parts'),
 ('Protocol'),
 ('Psycho: Collector\'s Edition'),
 ('Psycho: Collector\'s Edition (1998)'),
 ('Pump Up The Volume'),
 ('Pure Country'),
 ('Purple Rain'),
 ('Quest'),
 ('Quest For Camelot: Special Edition'),
 ('R.E.M. Road Movie'),
 ('Rage: Carrie 2: Special Edition'),
 ('Raging Bull'),
 ('Rain Man'),
 ('Rainmaker'),
 ('Raising Cain'),
 ('Real Blonde'),
 ('Real McCoy'),
 ('Reality Bites'),
 ('Reap The Wild Wind'),
 ('Rebel Without A Cause: Special Edition'),
 ('Red Corner: Special Edition'),
 ('Red Dawn'),
 ('Red Hot Chili Peppers: Funky Monks'),
 ('Red River'),
 ('Red Violin, The'),
 ('Relic'),
 ('Retroactive'),
 ('Revenge Of The Pink Panther'),
 ('Richard III'),
 ('Right Stuff'),
 ('Risky Business'),
 ('River'),
 ('River Wild'),
 ('River Wild (DTS)'),
 ('Road Warrior'),
 ('Rob Roy (1995)'),
 ('Robert De Niro Collection'),
 ('Robin Hood: Prince of Thieves'),
 ('Rocky'),
 ('Rocky II'),
 ('Rocky IV'),
 ('Rod Stewart: Storyteller 1984-1991'),
 ('Rollerball: Special Edition'),
 ('Rollercoaster'),
 ('Rolling Stones: Bridges To Babylon: Live In Concert'),
 ('Romeo And Juliet'),
 ('Ron Howard Signature Collection'),
 ('Ronin'),
 ('Rooster Cogburn'),
 ('Rosewood'),
 ('Roustabout'),
 ('Rugrats Movie'),
 ('Rumble Fish'),
 ('Rumble In The Bronx'),
 ('Run Silent, Run Deep'),
 ('Runaway Bride'),
 ('Runaway Train'),
 ('Running On Empty'),
 ('Rush Hour: Platinum Edition'),
 ('Saint: Special Edition'),
 ('Salem\'s Lot'),
 ('Scarecrow'),
 ('Scarface: Collector\'s Edition'),
 ('Scent of a Woman'),
 ('School Ties'),
 ('Scooby Doo\'s Original Mysteries'),
 ('Scorpio'),
 ('Scrooged'),
 ('Sea of Love'),
 ('Sea Wolves'),
 ('Searchers'),
 ('Secret Garden'),
 ('Secret Of My Success'),
 ('Secret Of N.I.M.H.'),
 ('Selena'),
 ('Set It Off'),
 ('Seven'),
 ('Seven Brides For Seven Brothers (MGM/UA)'),
 ('Seven Brides For Seven Brothers (Warner)'),
 ('Seven Days In May'),
 ('Sgt. Bilko'),
 ('Shadow'),
 ('Shadow (DTS)'),
 ('Shaft In Africa'),
 ('Shaft\'s Big Score'),
 ('Shaft: Special Edition'),
 ('Shallow Grave (MGM/UA)'),
 ('Sharky\'s Machine'),
 ('Shattered Image'),
 ('Shawshank Redemption'),
 ('Shine'),
 ('Shining'),
 ('Shocker'),
 ('Short #1'),
 ('Short #2 Dreams (Discontinued)'),
 ('Short #2: Dreams (Remastered)'),
 ('Short #3: Authority'),
 ('Short #4: Seduction'),
 ('Short #6: Insantiy'),
 ('Short #7: Utopia'),
 ('Short #8: Vision'),
 ('Short Cinema Journal 1:1 Invention'),
 ('Short Cinema Journal 1:3 Authority'),
 ('Short Cuts: Special Edition'),
 ('Shot In The Dark: Pink Panther'),
 ('Show Boat (Warner)'),
 ('Showboat (MGM/UA)'),
 ('Showdown In Little Tokyo'),
 ('Showgirls'),
 ('Silent Fall'),
 ('Simple Plan'),
 ('Simple Wish'),
 ('Singin\' In The Rain (MGM/UA)'),
 ('Singin\' In The Rain (Warner)'),
 ('Singles'),
 ('Slap Shot'),
 ('Sleepers'),
 ('Sleepy Hollow'),
 ('Sliding Doors'),
 ('Smiths: The Complete Picture'),
 ('Smokey And The Bandit'),
 ('Snake Eyes'),
 ('Sneakers'),
 ('Snow Falling On Cedars: Collector\'s Edition'),
 ('Soldier'),
 ('Soldier\'s Story: Special Edition'),
 ('Some Like It Hot'),
 ('Something To Talk About'),
 ('Somewhere In Time'),
 ('Sommersby'),
 ('Sorcerer'),
 ('Sour Grapes'),
 ('South Central'),
 ('South Park #1'),
 ('South Park #2'),
 ('South Park #3'),
 ('South Park #4'),
 ('South Park #5'),
 ('South Park #6'),
 ('South Park 3-Pack #1'),
 ('South Park 3-Pack #2'),
 ('South Park: Bigger, Longer And Uncut'),
 ('Space Jam'),
 ('Space Jam: Special Edition'),
 ('Spaceballs: Special Edition'),
 ('Spartacus'),
 ('Spawn: The Movie: Platinum Edition'),
 ('Special Edition Gift Set'),
 ('Specialist'),
 ('Species'),
 ('Species 2: Special Edition'),
 ('Speechless'),
 ('Sphere: Special Edition'),
 ('Spies Like Us'),
 ('Spitfire Grill'),
 ('Splendor In The Grass'),
 ('Spy Who Loved Me'),
 ('Spy Who Loved Me: Special Edition'),
 ('Stagecoach'),
 ('Stalag 17'),
 ('Stand And Deliver'),
 ('Stanley Kubrick Collection'),
 ('Star 80'),
 ('Star Is Born: Special Edition'),
 ('Star Trek Generation Movie Collection'),
 ('Star Trek III: The Search For Spock'),
 ('Star Trek IV: The Voyage Home'),
 ('Star Trek V: The Final Frontier'),
 ('Star Trek VI: The Undiscovered Country'),
 ('Star Trek: First Contact'),
 ('Star Trek: Generations'),
 ('Star Trek: Insurrection'),
 ('Star Trek: The Original Series, Volume 1'),
 ('Star Trek: The Original Series, Volume 10'),
 ('Star Trek: The Original Series, Volume 11'),
 ('Star Trek: The Original Series, Volume 2'),
 ('Star Trek: The Original Series, Volume 3'),
 ('Star Trek: The Original Series, Volume 4'),
 ('Star Trek: The Original Series, Volume 5'),
 ('Star Trek: The Original Series, Volume 6'),
 ('Star Trek: The Original Series, Volume 7'),
 ('Star Trek: The Original Series, Volume 8'),
 ('Star Trek: The Original Series, Volume 9'),
 ('Star Trek: The Original Series; Volume 12'),
 ('Stargate SG-1'),
 ('Stay Tuned'),
 ('Stealing Home'),
 ('Steven Seagal Collection'),
 ('Stigmata: Special Edition'),
 ('Sting'),
 ('Storefront Hitchcock: Robyn Hitchcock'),
 ('Story Of Us'),
 ('Strangers On A Train'),
 ('Street Fighter: Collector\'s Edition'),
 ('Streetcar Named Desire: Director\'s Cut'),
 ('Streets Of Fire'),
 ('Striptease'),
 ('Stroker Ace'),
 ('Sudden Death'),
 ('Superstar'),
 ('Surviving The Game'),
 ('Swan Lake: Tchaikovsky: Matthew Bourne'),
 ('Swashbuckler'),
 ('Sweet Hereafter: Platinum Edition'),
 ('Switchback'),
 ('Taffin'),
 ('Taking Of Pelham One Two Three'),
 ('Talented Mr. Ripley: Special Edition'),
 ('Tango & Cash'),
 ('Tarzan And The Lost City'),
 ('Tea With Mussolini'),
 ('Teenage Mutant Ninja Turtles: The Movie'),
 ('Ten Commandments'),
 ('Tequila Sunrise'),
 ('That Old Feeling'),
 ('That\'s Entertainment!'),
 ('Theatrical Hits Gift Set'),
 ('Thelma & Louise: Special Edition'),
 ('They Were Expendable'),
 ('Thief: Special Edition'),
 ('Thin Line Between Love & Hate'),
 ('Thing: Collector\'s Edition'),
 ('Thomas Crown Affair: Special Edition (1968)'),
 ('Thomas Crown Affair: Special Edition'),
 ('Three Kings: Special Edition'),
 ('Three Tenors in Concert 1994'),
 ('Three Tenors: Paris 1998: Carreras/Domingo/Pavarotti'),
 ('Three To Tango'),
 ('Thumbelina'),
 ('Thunder Road'),
 ('Thunderball: Special Edition'),
 ('Thunderbolt And Lightfoot'),
 ('Time to Kill (Warner)'),
 ('Timecop'),
 ('Tin Cup'),
 ('Titanic'),
 ('To Kill a Mockingbird: Collector\'s Edition'),
 ('Tom And Jerry\'s Greatest Chases'),
 ('Tom Clancy Thrillers Gift Set'),
 ('Tom Cruise Action Pack Gift Set'),
 ('Tom Petty & The Heartbreakers: High Grass Dogs: Live'),
 ('Tom Sawyer (MGM/UA)'),
 ('Tommy Boy'),
 ('Tomorrow Never Dies'),
 ('Tomorrow Never Dies: Special Edition (Discontinued)'),
 ('Top Gun'),
 ('Total Eclipse'),
 ('Train: Special Edition'),
 ('Trekkies'),
 ('Tremors 2: Aftershocks'),
 ('Tremors: Collector\'s Edition'),
 ('Trial And Error'),
 ('Trick'),
 ('Trigger Effect'),
 ('True Crime (Warner)'),
 ('True Grit'),
 ('True Romance: Director\'s Cut'),
 ('True Stories: Talking Heads'),
 ('Truman Show, The'),
 ('Tumbleweeds'),
 ('Twilight'),
 ('Twilight Zone Volume 1'),
 ('Twilight Zone Volume 10'),
 ('Twilight Zone Volume 11'),
 ('Twilight Zone Volume 12'),
 ('Twilight Zone Volume 13'),
 ('Twilight Zone Volume 14'),
 ('Twilight Zone Volume 15'),
 ('Twilight Zone Volume 16'),
 ('Twilight Zone Volume 17'),
 ('Twilight Zone Volume 18'),
 ('Twilight Zone Volume 19'),
 ('Twilight Zone Volume 2'),
 ('Twilight Zone Volume 20'),
 ('Twilight Zone Volume 21'),
 ('Twilight Zone Volume 22'),
 ('Twilight Zone Volume 23'),
 ('Twilight Zone Volume 3'),
 ('Twilight Zone Volume 4'),
 ('Twilight Zone Volume 5'),
 ('Twilight Zone Volume 6'),
 ('Twilight Zone Volume 7'),
 ('Twilight Zone Volume 8'),
 ('Twilight Zone Volume 9'),
 ('Twins'),
 ('Twister'),
 ('Twister: Special Edition'),
 ('Two If By Sea'),
 ('Two Jakes'),
 ('Two Minute Warning'),
 ('U.S. Marshals: Special Edition'),
 ('U2: Rattle & Hum'),
 ('Ulee\'s Gold'),
 ('Uncle Buck'),
 ('Under Siege'),
 ('Under Siege 2: Dark Territory'),
 ('Underneath'),
 ('Unforgiven'),
 ('Usual Suspects'),
 ('Van Halen Live: Right Here, Right Now'),
 ('Van Halen: Video Hits #1'),
 ('Varsity Blues'),
 ('Vegas Vacation'),
 ('Vertigo: Collector\'s Edition'),
 ('Victory'),
 ('Videodrome'),
 ('Village Of The Damned'),
 ('Virtuosity'),
 ('Virus'),
 ('Virus: Collector\'s Edition'),
 ('Vision Quest'),
 ('Viva Las Vegas'),
 ('Wag The Dog: Platinum Edition'),
 ('War'),
 ('War Of The Worlds'),
 ('War Wagon'),
 ('WarGames: Special Edition'),
 ('Warriors Of Virtue'),
 ('Waterworld'),
 ('Waterworld (DTS)'),
 ('Wedding Singer'),
 ('West Side Story'),
 ('Westworld'),
 ('What Ever Happened to Baby Jane?'),
 ('White Sands'),
 ('Who\'s Afraid of Virginia Woolf?'),
 ('Why Do Fools Fall In Love'),
 ('Wild America'),
 ('Wild Bunch: Director\'s Cut'),
 ('Wild Wild West: Special Edition'),
 ('Willy Wonka & The Chocolate Factory'),
 ('Winning'),
 ('Witches'),
 ('Witches of Eastwick'),
 ('With Honors'),
 ('Without Limits'),
 ('Witness (Paramount)'),
 ('Wiz'),
 ('Wizard of Oz'),
 ('Wizard Of Oz: Deluxe Edition'),
 ('Wizard Of Oz: Special Edition'),
 ('Wolf Man: Classic Monster Collection'),
 ('Woman of The Year'),
 ('Wood'),
 ('Woodstock: Three Days Of Peace & Music: The Director\'s Cut'),
 ('World Is Not Enough: Special Edition'),
 ('Wrongfully Accused'),
 ('Xanadu'),
 ('Yellow Submarine: Special Edition'),
 ('You\'ve Got Mail'),
 ('Young Cinematographer'),
 ('Young Guns 2'),
 ('Young Hercules'),
 ('Zero Effect'),
 ('Hurricane, The:Special Edition'),
 ('Isn\'t She Great'),
 ('Ride with the Devil'),
 ('Arsenic And Old Lace'),
 ('Bronco Billy'),
 ('National Velvet'),
 ('North by Northwest: Special Edition'),
 ('Trial  by Jury'),
 ('Diabolique'),
 ('Henry V'),
 ('Interiors'),
 ('Love And Death'),
 ('Manhattan'),
 ('Princess Bride'),
 ('Sleeper'),
 ('Stardust Memories'),
 ('Woody Allen Collection'),
 ('Star Trek II: The Wrath of Khan'),
 ('My Dog Skip: Special Edition'),
 ('Angela\'s Ashes'),
 ('Beethoven\'s 3rd'),
 ('Boogie Nights: Platinum Edition (2 Disc Set)'),
 ('Active Stealth: Special Edition'),
 ('Magnolia: Platinum Edition'),
 ('Searching For Bobby Fischer'),
 ('Star Trek #13'),
 ('Star Trek #14'),
 ('Where\'s Marlowe'),
 ('Kalifornia: Special Edition (Re-release)'),
 ('Platoon (Movie-Only Edition)'),
 ('Fargo'),
 ('Metallica: With The San Francisco Symphony: S & M (Clean Version)'),
 ('Nashville (Special Edition)'),
 ('Braveheart (Special Edition)'),
 ('Whole Nine Yards (Special Edition)'),
 ('Boiler Room'),
 ('Big Tease'),
 ('K.D. Lang: Harvest Of Seven Years: Cropped And Chronicled'),
 ('Misery'),
 ('Phantasm 4: Oblivion'),
 ('Pumpkinhead'),
 ('Six Degrees Of Separation'),
 ('Stonebrook'),
 ('Swamp Thing'),
 ('Texas Chainsaw Massacre 2'),
 ('They Were Expendable'),
 ('Pretty Maids All In a Row'),
 ('Deterrence: Special Edition'),
 ('Abbott And Costello Meet Frankenstein: Classic Monster Collection'),
 ('Creature From The Black Lagoon: Classic Monster Collection'),
 ('Invisible Man: Classic Monster Collection'),
 ('Phantom Of The Opera (Special Edition/ 1943)'),
 ('Classic Monsters Collection (Special Edition)'),
 ('Playboy Wet And Wild #9: Slippery When Wet'),
 ('Tycus (Special Edition)'),
 ('Adam\'s Rib'),
 ('Dark Victory'),
 ('Jezebel'),
 ('Next Best Thing'),
 ('Jurassic Park (Special Edition)'),
 ('Lost World: Jurassic Park (Special Edition/ Dolby Digital)'),
 ('Twin Peaks: Fire Walk with Me'),
 ('3 Strikes'),
 ('Amityville Horror'),
 ('Beach Party'),
 ('Bikini Beach'),
 ('Bucket Of Blood'),
 ('Delta Force'),
 ('Delta Force 2'),
 ('Dillinger'),
 ('Frogs'),
 ('Heavy Traffic'),
 ('Jurassic Park (Special Edition)'),
 ('Jurassic Park Collection (Limited Special Edition)'),
 ('Jurassic Park Collection (Special Edition)'),
 ('Lost World: Jurassic Park (Special Edition)'),
 ('Pajama Party'),
 ('Stranger Than Paradise'),
 ('Supernova'),
 ('Tales Of Terror'),
 ('This Is Spinal Tap (Special Edition)'),
 ('American Psycho (Unrated)'),
 ('Afrocentricity'),
 ('42nd Street'),
 ('Good News'),
 ('Take Me Out To The Ball Game'),
 ('50 Years War: Israel And The Arabs'),
 ('Butterfield 8'),
 ('Christmas Carol'),
 ('Pat And Mike'),
 ('Unsinkable Molly Brown'),
 ('Erin Brockovich'),
 ('Naked Gun, The: From the Files of Police Squad'),
 ('Naked Gun 2 1/2: The Smell of Fear'),
 ('Naked Gun 33 1/3: The Final Insult'),
 ('Shane (Special Edition)'),
 ('American Psycho (R-Rated)'),
 ('Romeo Must Die'),
 ('Beyond The Mat: Collector\'s Edition (Unrated Version)'),
 ('Big Kahuna'),
 ('Dragonheart: A New Beginning'),
 ('7 Faces Of Dr. Lao'),
 ('Bad Moon'),
 ('Batman Beyond: Return Of The Joker'),
 ('Scooby Doo And The Alien Invaders'),
 ('Tom Thumb (Special Edition)'),
 ('Playboy: Sexy Girls Next Door'),
 ('Adventures of the Wilderness Family'),
 ('Angel'),
 ('New Barbarians'),
 ('Proud And The Damned'),
 ('Trial By Jury'),
 ('American Beauty (Special Edition)'),
 ('Elvis \'68 Comeback Special'),
 ('Elvis: One Night With You'),
 ('Charlie Brown Christmas/ It\'s Christmastime Again, Charlie Brown'),
 ('Charlie Brown Thanksgiving/ The Mayflower Voyages'),
 ('It\'s The Great Pumpkin, Charlie Brown/ You\'re Not Elected, Charlie Brown'),
 ('Peanuts Classic Holiday Collection'),
 ('How The West Was Won'),
 ('Year Of Living Dangerously'),
 ('Enter The Dragon: Collector\'s Edition'),
 ('Ministry: Tapes Of Wrath'),
 ('Rosemary\'s Baby'),
 ('Dead Zone'),
 ('Pet Sematary'),
 ('Diamonds Are Forever: Special Edition'),
 ('From Russia With Love (Special Edition)'),
 ('Living Daylights (Special Edition)'),
 ('Never Say Never Again'),
 ('Octopussy (Special Edition)'),
 ('View To A Kill: Special Edition'),
 ('You Only Live Twice (Special Edition)'),
 ('James Bond Collection #3 (Special Edition)'),
 ('Final Destination: Platinum Edition'),
 ('Any Given Sunday'),
 ('Elvis: That\'s The Way It Is'),
 ('Treasures Of The Twilight Zone'),
 ('2010 (a.k.a. Two Thousand And Ten)'),
 ('Beyond The Mat (Special Edition/ R Rated Version)'),
 ('Brainstorm'),
 ('Logan\'s Run: Special Edition'),
 ('Westworld'),
 ('Jurassic Park (Special Edition/ Pan & Scan/ Dolby Digital)'),
 ('Circuit #7'),
 ('Jurassic Park Collection (Special Edition/ Pan & Scan)'),
 ('Lost World: Jurassic Park (Special Edition/ Pan & Scan/ Dolby Digital)'),
 ('Rules Of Engagement (Special Edition)'),
 ('La Femme Nikita'),
 ('Gladiator'),
 ('Passion Of Mind'),
 ('Playboy Centerfold: Jodi Ann Paterson: 2000 Playmate Of The Year'),
 ('Playboy Girls Of Hedonism'),
 ('Playboy Lusty Latin Ladies'),
 ('Playboy No Boys Allowed'),
 ('RPM (Special Edition)'),
 ('Star Trek TV #15: Operation Annihilate!/ Catspaw'),
 ('Star Trek TV #16: Metamorphosis/ Friday\'s Child'),
 ('Annie Get Your Gun (Special Edition)'),
 ('Casper\'s Haunted Christmas'),
 ('Chasers'),
 ('Friday The 13th: Part 3'),
 ('Friday The 13th: The Final Chapter'),
 ('Friendly Persuasion'),
 ('Gettysburg: Special Edition'),
 ('How The Grinch Stole Christmas / Horton Hears A Who (Special Edition)'),
 ('Imaginary Crimes'),
 ('Nutty Professor (1963)'),
 ('R.E.M.: Parallel'),
 ('R.E.M.: Pop Screen'),
 ('R.E.M.: This Film Is On'),
 ('R.E.M.: Tourfilm'),
 ('Somewhere In Time: 20th Anniversary Edition'),
 ('South Park: Christmas In South Park'),
 ('South Park: The Chef Experience'),
 ('Touch Of Evil'),
 ('Year Without A Santa Claus'),
 ('Ready To Rumble: Special Edition'),
 ('Simpatico'),
 ('Snow Day (Special Edition)'),
 ('Friday Fresh Pack: Friday/ Next Friday (Special Edition)'),
 ('Madonna: Music'),
 ('Powers Pack: Austin Powers (Special Edition)/ Spy Who Shagged Me (Special Edition)'),
 ('Benny And Joon: Special Edition'),
 ('Jean Claud Van Damme 2-Pack'),
 ('Love And Basketball: Platinum Edition'),
 ('Skulls (Special Edition)'),
 ('U-571 (Special Edition)'),
 ('Kevin Costner 2-Pack'),
 ('Cats'),
 ('Return To Me'),
 ('Al Pacino Collection: Devil\'s Advocate/ Dog Day Afternoon/ Heat'),
 ('Batman Legacy: Batman/ Batman Returns/ Batman Forever/ Batman And Robin'),
 ('Extreme Chan Action Pack: First Strike/ Mr. Nice Guy/ Rumble In The Bronx'),
 ('Grumpy Old Men / Grumpier Old Men'),
 ('House Party Party Pack: House Party 1-3'),
 ('Humphrey Bogart Collection'),
 ('John Wayne Collection: The Cowboys / The Searchers/ Stagecoach'),
 ('Lethal Weapon Legacy #1-3 (Director\'s Cut)'),
 ('Robert De Niro 2-Pack'),
 ('Filth And The Fury: The Sex Pistols'),
 ('X-Men Animated Series: Phoenix Saga'),
 ('Talk Radio'),
 ('Deal Of A Lifetime'),
 ('Flintstones: Viva Rock Vegas'),
 ('Playboy 2001 Playmate Calendar'),
 ('Playboy Best Of College Girls'),
 ('Playboy Sex Court'),
 ('Playboy Shagalicious British Babes'),
 ('Powerpuff Girls: Down And Dirty'),
 ('Powerpuff Girls: Powerpuff Bluff'),
 ('Short: International Release'),
 ('Frequency'),
 ('Gossip'),
 ('Luciano Pavarotti: The Recital'),
 ('Airplane!'),
 ('Airplane 2: The Sequel'),
 ('Bounty'),
 ('Class'),
 ('Code Of Silence'),
 ('Escape From New York'),
 ('Malice'),
 ('Submerged'),
 ('Tucker: The Man And His Dream'),
 ('Star Trek TV #17: Who Mourns For Adonis/ Amok Time'),
 ('Star Trek TV #18: The Doomsday Machine/ Wolf In The Fold'),
 ('Nightmare On Elm Street 2: Freddy\'s Revenge'),
 ('Nightmare On Elm Street 3: Dream Warriors'),
 ('Nightmare On Elm Street 4: The Dream Maker'),
 ('Nightmare On Elm Street 5: The Dream Child'),
 ('Freddy\'s Dead: The Final Nightmare'),
 ('Wes Craven\'s New Nightmare'),
 ('Bananas'),
 ('Best Years Of Our Lives (MGM/UA)'),
 ('Blue\'s Big Musical Movie: Blue\'s Clues'),
 ('Boiler Room: Platinum Edition'),
 ('Clint Eastwood Collection Gift Set'),
 ('Democrats: The American Experience Presidents Collection'),
 ('Easy Money (MGM/UA)'),
 ('Everything You Always Wanted To Know About Sex But Were Afraid To Ask'),
 ('It\'s The Pied Piper, Charlie Brown'),
 ('Lethal Weapon 4: Premiere Collection'),
 ('Liberty Heights'),
 ('Life Beyond Earth'),
 ('Republicans: The American Experience Presidents Collection'),
 ('Short #9: Trust'),
 ('Big Sleep (Warner)'),
 ('But I\'m A Cheerleader'),
 ('Flinstones: Viva Rock Vegas'),
 ('Jailhouse Rock (Warner)'),
 ('Jurassic Park Collection: Collector\'s Edition'),
 ('Jurassic Park Collection: Limited Collector\'s Edition'),
 ('Jurassic Park: Lost World: Collector\'s Edition (DTS)'),
 ('Land Before Time 7: The Stone Of Cold Fire'),
 ('8 1/2 Women'),
 ('How The West Was Won (Discontinued)'),
 ('Jurassic Park: Lost World: Collector\'s Edition'),
 ('Playboy: Sex Court'),
 ('Screwed'),
 ('Billy Jack (Warner)'),
 ('Born On The Fourth Of July: Collector\'s Edition'),
 ('Stephen Hawking\'s Universe'),
 ('Strangers On A Train (Remastered Version)'),
 ('Playboy: Best Of College Girls'),
 ('U-571: Collector\'s Edition'),
 ('Pitch Black: Collector\'s Edition (R Rated Version)'),
 ('Playboy: 2001 Playmate Calendar'),
 ('Playboy: Shagalicious British Babes'),
 ('Skulls: Collector\'s Edition'),
 ('Crush (Warner)'),
 ('Elvis: That\'s The Way It Is (Discontinued)'),
 ('Pitch Black: Collector\'s Edition (Unrated Version)'),
 ('Year Of Living Dangerously (Discontinued)'),
 ('Mission Impossible 2: Special Edition'),
 ('American Pimp (MGM/UA)'),
 ('Star Trek: The Original Series, Volume 17'),
 ('Star Trek: The Original Series, Volume 18'),
 ('Planes, Trains And Automobiles'),
 ('She\'s Having A Baby'),
 ('Still Smokin\''),
 ('Up In Smoke'),
 ('White Christmas (Special Edition)'),
 ('White Christmas: Special Edition'),
 ('Jim Carrey 2-Pack'),
 ('Perfect Storm: Special Edition'),
 ('Perfect Storm: Autographed Collector\'s Edition'),
 ('Perfect Storm: Collector\'s Edition'),
 ('Perfect Storm: Platinum Mini-Box Collector\'s Edition'),
 ('League Of Gentlemen: Series #1: Special Edition'),
 ('Running Mates'),
 ('Short #10: Chaos'),
 ('Luis Miguel: Vivo'),
 ('Morrissey: Oye Esteban!'),
 ('Legend: Special Edition'),
 ('Pokemon: The Movie 2000'),
 ('Alamo'),
 ('At Close Range'),
 ('Attention Shoppers'),
 ('Bat 21'),
 ('Breaker! Breaker!'),
 ('Breakheart Pass'),
 ('Dirty Pictures'),
 ('Gorky Park'),
 ('House Of Games'),
 ('Kill Me Again'),
 ('Mouse On The Moon'),
 ('Rancho Deluxe'),
 ('Sid And Nancy (Movie-Only Edition)'),
 ('Price Of Glory: Special Edition'),
 ('Beethoven: Symphony 4 & 5: Daniel Barenboim (DVD-Audio)'),
 ('Hommage A L\'Orchestre Lamoureux: Yutaka Sado (DVD-Audio)'),
 ('Jazz At The Movies: The Bedroom Mixes (DVD-Audio)'),
 ('Natalie Merchant: Tigerlily (DVD-Audio)'),
 ('Strauss: Johann Strauss In Berlin: Nikolaus Harnoncourt (DVD-Audio)'),
 ('In Crowd: Special Edition'),
 ('Stone Temple Pilots: Core (DVD-Audio)'),
 ('Eddie Murphy Collection: Bowfinger/ Life/ The Nutty Professor 1 & 2'),
 ('Nutty Professor 2: The Klumps: Special Edition'),
 ('Short: International Release #2'),
 ('Jaws (Special Edition/ Pan & Scan/ Dolby Digital)'),
 ('Our Lips Are Sealed'),
 ('National Geographic: The Ultimate National Geographic Collection'),
 ('Brandy: The Videos'),
 ('Corrs: Live At The Royal Albert Hall'),
 ('Hootie And The Blowfish: Summer Camp With Trucks'),
 ('Sugar Ray: No Cerveza, No Trabaja'),
 ('Survivor: Season #1: The Greatest And Most Outrageous Moments'),
 ('Tori Amos: The Complete Videos 1992-1998'),
 ('Cutting Edge'),
 ('In The Heat Of The Night: Special Edition'),
 ('Love Field'),
 ('Man In The Moon'),
 ('Moll Flanders'),
 ('Mystic Pizza'),
 ('Organization'),
 ('They Call Me Mister Tibbs'),
 ('Untamed Heart'),
 ('When Harry Met Sally: Special Edition'),
 ('Wonder Boys: Special Edition'),
 ('Alice\'s Restaurant: Special Edition'),
 ('Black Caesar: Special Edition'),
 ('Black Mama, White Mama'),
 ('Coffy: Special Edition'),
 ('Cotton Comes To Harlem'),
 ('Dance With A Stranger'),
 ('Desert Hearts: Special Edition'),
 ('Foxy Brown: Special Edition'),
 ('Friday Foster'),
 ('I\'m Gonna Git You Sucka'),
 ('River\'s Edge'),
 ('Sheba Baby'),
 ('Shaft (2000)'),
 ('Children of a Lesser God'),
 ('Conversation: Special Edition'),
 ('Odd Couple'),
 ('Officer and a Gentleman: Special Edition'),
 ('9 1/2 Weeks'),
 ('Pop And Me: Special Edition'),
 ('Virgin Suicides'),
 ('Body Shots'),
 ('Replacements: Special Edition'),
 ('Slaughter'),
 ('Slaughter\'s Big Rip-Off'),
 ('Truck Turner'),
 ('American Buffalo'),
 ('Babette\'s Feast'),
 ('Bride Wore Black'),
 ('Camille Claudel'),
 ('I Shot Andy Warhol'),
 ('Jean De Florette'),
 ('Longtime Companion'),
 ('Man Who Loved Women'),
 ('Manon Of The Spring'),
 ('Mississippi Mermaid'),
 ('Small Change'),
 ('Story Of Adele H.'),
 ('Suture'),
 ('Cell: Special Edition'),
 ('Saving Grace'),
 ('Art of War'),
 ('Seven: Platinum Edition'),
 ('Autumn In New York'),
 ('Baller Blockin'),
 ('Bring It On: Special Edition'),
 ('MVP: Most Valuable Primate: Special Edition'),
 ('Time Machine (DVD Only)'),
 ('Moonlight And Valentino'),
 ('Mermaids'),
 ('Baby Boom'),
 ('Adventures Of Rocky And Bullwinkle'),
 ('Bird'),
 ('Circuit #8'),
 ('Cotton Mary'),
 ('Eyes Of Tammy Faye'),
 ('Jazz'),
 ('Jesus\' Son'),
 ('Playboy California Girls'),
 ('Playboy Sexy Shorts'),
 ('Race Against Time'),
 ('Round Midnight: Special Edition'),
 ('Saving Grace: Special Edition'),
 ('Starry Night'),
 ('Thelonius Monk: Straight, No Chaser'),
 ('Crime And Punishment In Suburbia: Special Edition'),
 ('Mr. Accident'),
 ('Beethoven: Symphony 1 & 2: Daniel Barenboim (DVD-Audio)'),
 ('Beethoven: Symphony 3: Daniel Barenboim (DVD-Audio)'),
 ('Beethoven: Symphony 6: Pastorale: Daniel Barenboim (DVD-Audio)'),
 ('Beethoven: Symphony 7 & 8: Daniel Barenboim (DVD-Audio)'),
 ('Beethoven: Symphony 9: Daniel Barenboim (DVD-Audio)'),
 ('Bela Fleck: The Bluegrass Sessions: Acoustic Planet #2 (DVD-Audio)'),
 ('Buena Vista Social Club: Buena Vista Social Club (DVD-Audio)'),
 ('Neil Young: Road Rock #1 (DVD-Audio)'),
 ('Steely Dan: Two Against Nature (DVD-Audio)'),
 ('Corrs: In Blue (DVD-Audio)'),
 ('Deep Purple: Machine Head (DVD-Audio)'),
 ('Doors: L.A. Woman (DVD-Audio)'),
 ('Firesign Theatre: Boom Dot Bust (DVD-Audio)'),
 ('K.D. Lang: Invincible Summer (DVD-Audio)'),
 ('Neil Young: Red Rocks Live'),
 ('Untouchables, The'),
 ('Death Wish'),
 ('Abominable Dr. Phibes'),
 ('Attack Of The Puppet People'),
 ('Blue Sky'),
 ('Cherry 2000'),
 ('City Of Industry'),
 ('Deadline'),
 ('Die Monster Die!'),
 ('Double Impact'),
 ('Dr. Phibes Rises Again'),
 ('Emerald Forest'),
 ('End'),
 ('Exorcist: The Version You\'ve Never Seen: Special Edition'),
 ('Fatal Beauty'),
 ('Fuzz'),
 ('Harley Davidson And The Marlboro Man'),
 ('JFK: Special Edition'),
 ('Losin\' It'),
 ('Man From Planet X'),
 ('Mighty Quinn'),
 ('Friends: The Best Of Friends #1'),
 ('Friends: The Best Of Friends #2'),
 ('Friends: The Best Of Friends Gift Set #1 & 2: Top 10 Episodes'),
 ('Greeks: Crucible Of Civilization: Special Edition'),
 ('Juice'),
 ('Kiss Me Guido: Special Edition'),
 ('Longest Yard'),
 ('Navy Seals'),
 ('Necessary Roughness'),
 ('North Dallas Forty'),
 ('Wild Angels'),
 ('Heaven And Earth: Special Edition'),
 ('Natural Born Killers (Theatrical Version/ Special Edition)'),
 ('Warriors'),
 ('Playboy Really Naked Truth'),
 ('Playboy Strip Search: Backstage'),
 ('Being There'),
 ('Affair Of Love'),
 ('Five Senses'),
 ('Harvey'),
 ('Fantasticks: Special Edition'),
 ('In Pursuit: Special Edition'),
 ('Kings And Queens Of Comedy Gift Set'),
 ('Original Kings Of Comedy'),
 ('Queens Of Comedy'),
 ('Ben Hur'),
 ('Man Who Knew Too Much (1956)'),
 ('Mother (1996)'),
 ('Ordinary People'),
 ('Real Life'),
 ('Rear Window: Special Edition'),
 ('Rope'),
 ('Saboteur'),
 ('Shadow Of A Doubt'),
 ('Star Trek TV #19: The Changeling/ The Apple'),
 ('Star Trek TV #20: Mirror Mirror/ The Deadly Years'),
 ('Terms Of Endearment: Special Edition'),
 ('Topaz'),
 ('Torn Curtain'),
 ('Trouble With Harry'),
 ('Nuremberg (Discontinued)'),
 ('Playboy Complete Anna Nicole Smith'),
 ('Playboy Girls Down Under: Surviving The Australian Outback'),
 ('Porky\'s/ Porky\'s 2: The Next Day'),
 ('Bait: Special Edition'),
 ('Battlefield Earth: Special Edition'),
 ('12 Angry Men'),
 ('Short: International Release #3'),
 ('Reversal Of Fortune: Special Edition'),
 ('Defending Your Life'),
 ('Empire Records'),
 ('Lost Weekend'),
 ('Red Letters: Special Edition'),
 ('Short #11: Ecstasy'),
 ('Luis Miguel: Vivo Gift Set (Limited Edition DVD & CD)'),
 ('Oliver Stone Collection 6-Pack: Special Edition'),
 ('Alfie'),
 ('Best Of Hitchcock #1'),
 ('Best Of Hitchcock #2'),
 ('Bless The Child: Special Edition'),
 ('Evening Star: Special Edition'),
 ('Family Plot'),
 ('Frenzy'),
 ('Hitchcock Collection #2: Rear Window/ Man Who Knew Too Much (1956)/ Presents #4'),
 ('Joni Mitchell: Both Sides Now (DVD-Audio)'),
 ('Jose Cura: Verismo (DVD-Audio)'),
 ('Lost In America'),
 ('Mahler: Symphony 2: Zubin Mehta (DVD-Audio)'),
 ('Martin Lawrence: You So Crazy'),
 ('Orff: Carmina Burana: Zubin Mehta (DVD-Audio)'),
 ('Playboy Girls Of The Hard Rock Hotel And Casino'),
 ('Powerpuff Girls: The Mane Event (Special Edition)'),
 ('Take 6: Take 6 (DVD-Audio)'),
 ('Absolutely Fabulous: Complete DVD Collection'),
 ('Absolutely Fabulous: Series #1'),
 ('Absolutely Fabulous: Series #2'),
 ('Absolutely Fabulous: Series #3'),
 ('World According To Garp'),
 ('All Dogs Go To Heaven'),
 ('All Dogs Go To Heaven 2'),
 ('Big Country'),
 ('Birdman Of Alcatraz'),
 ('Bishop\'s Wife'),
 ('Elmer Gantry'),
 ('Fluke'),
 ('Fortune Cookie'),
 ('Getting Even With Dad'),
 ('Greatest Story Ever Told: Special Edition'),
 ('Hallelujah Trail'),
 ('Hans Christian Andersen'),
 ('Jackie Robinson Story'),
 ('Lilies Of The Field'),
 ('Lion In Winter'),
 ('Long Riders'),
 ('Meet The Parents'),
 ('Miracle Worker'),
 ('Napoleon'),
 ('Secret Of N.I.M.H. 2: Timmy To The Rescue'),
 ('Support Your Local Gunfighter'),
 ('Support Your Local Sheriff'),
 ('Vera Cruz'),
 ('Wild Bill'),
 ('Yours, Mine And Ours'),
 ('Tic Code'),
 ('Watcher'),
 ('Wonderland'),
 ('Tomorrow Never Dies: Collector\'s Edition'),
 ('Oliver Stone Collection 10-Pack: Special Edition'),
 ('Get Carter: Special Edition'),
 ('Lost Souls: Special Edition'),
 ('Madonna: The Immaculate Collection'),
 ('Madonna: The Video Collection 93:99'),
 ('B.B. King: Blues Summit'),
 ('Lucky Numbers: Special Edition'),
 ('Mo\' Better Blues'),
 ('Playboy Red Hot Redheads'),
 ('Roadshow: Misty Rain'),
 ('Spike Lee Collection: Crooklyn/ Jungle Fever/ Mo\' Better Blues'),
 ('Jesus Christ Superstar (2000)'),
 ('Little Vampire'),
 ('Old Man And The Sea'),
 ('Scooby Doo And The Witch\'s Ghost'),
 ('Scooby Doo On Zombie Island'),
 ('Adjuster'),
 ('Boxing Helena'),
 ('Fellini Satyricon'),
 ('Fellini\'s Roma'),
 ('How I Won The War'),
 ('King Of Heart'),
 ('Live Flesh'),
 ('Mach 2: Special Edition'),
 ('Playboy Best Of Pamela Anderson (Universal)'),
 ('Playboy Girlfriends #1 (Universal)'),
 ('Playboy Girlfriends #2 (Universal)'),
 ('Playboy Real Couples: Sex In Dangerous Places (Universal)'),
 ('Rocky: Special Edition'),
 ('Rocky Gift Set: Rocky 1-5'),
 ('Tank Girl'),
 ('Women On The Verge Of A Nervous Breakdown'),
 ('Tom Petty: Playback'),
 ('Dancer In The Dark'),
 ('Red Planet'),
 ('Bix Beiderbeck: Ain\'t None Of Them Play Like Him Yet'),
 ('Election 2000: CNN'),
 ('Playboy 2000 Playmate Calendar'),
 ('Playboy Asian Exotica'),
 ('Hendrix'),
 ('Playboy Best Of Jenny McCarthy'),
 ('Playboy Freshman Class'),
 ('Amos And Andrew'),
 ('Apache'),
 ('Blame It On Rio'),
 ('Bon Jovi: The Crush Tour'),
 ('Buffalo Bill And The Indians, Or Sitting Bull\'s History Lesson'),
 ('Canadian Bacon'),
 ('City Slickers'),
 ('Coneheads'),
 ('Eight Men Out'),
 ('Family Thing'),
 ('Frankie And Johnny'),
 ('Ghost (Special Edition)'),
 ('Home Of Our Own'),
 ('Horse Soldiers'),
 ('Kentuckian'),
 ('Ladies Man'),
 ('Love Story (Special Edition)'),
 ('Magnificent Seven (Special Edition)'),
 ('Mean Season'),
 ('Mississippi Burning (Special Edition)'),
 ('Paul Simon: You\'re The One: In Concert From Paris'),
 ('Pope Of Greenwich Village'),
 ('Posse'),
 ('Return Of The Magnificent Seven'),
 ('Rugrats In Paris: The Movie'),
 ('Semi-Tough'),
 ('Shag: The Movie'),
 ('Some Like It Hot (Movie-Only Edition)'),
 ('Some Like It Hot (Special Edition)'),
 ('Southern Comfort'),
 ('Star Trek TV #21: I, Mudd/ The Trouble With Tribbles'),
 ('Star Trek TV #22: Bread And Circuses/ Journey To Babel'),
 ('Stargate SG-1: Season #1'),
 ('Stuart Saves His Family'),
 ('Summer Rental'),
 ('Throw Momma From The Train'),
 ('Turn It Up'),
 ('Westerner'),
 ('Winter People'),
 ('Youngblood'),
 ('Bamboozled (Special Edition)'),
 ('Blackadder #1'),
 ('Blackadder #2'),
 ('Blackadder #3: Blackadder The Third'),
 ('Blackadder #4: Blackadder Goes Forth'),
 ('Blackadder #5: Blackadder Back And Forth'),
 ('Blackadder: The Complete Collector\'s Set'),
 ('Complete Superman Collection'),
 ('Father Ted: The Compete Series #1'),
 ('Little Nicky (Special Edition)'),
 ('Loving Jezebel'),
 ('Mummy: The Ultimate Edition (Special Edition/ 1999)'),
 ('Rio Bravo'),
 ('Superman 2'),
 ('Superman 3'),
 ('Superman 4: The Quest For Peace'),
 ('Superman: The Movie (Special Edition)'),
 ('Stargate SG-1 #2'),
 ('Return With Honor'),
 ('Allosaurus: A Walking With Dinosaurs Special'),
 ('Foreigner: Foreigner (DVD-Audio)'),
 ('Metallica: Metallica (DVD-Audio)'),
 ('Olu Dara: Neighborhoods (DVD-Audio)'),
 ('Playboy Celebrities'),
 ('Playboy Club Lingerie'),
 ('Playboy Playmates On The Catwalk'),
 ('Playboy Sexcetera'),
 ('Playboy Tales Of Erotic Fantasies'),
 ('Playboy Voluptuous Vixens #1'),
 ('Wives And Daughters'),
 ('Funny Face'),
 ('Paris When It Sizzles'),
 ('Sabrina'),
 ('Miss Congeniality (Special Edition)'),
 ('Space Cowboys'),
 ('Circuit #9'),
 ('Playboy Centerfold: Bernaola Twins: 2000 Playmate Of The Year'),
 ('Playboy Girls Next Door: Naughty And Nice'),
 ('Playboy Playmate Erotic Adventures'),
 ('Secrets Of Magic: Lance Burton'),
 ('AC/DC: No Bull'),
 ('Alice Cooper: Billion Dollar Babies (DVD-Audio)'),
 ('American Pie (Special Edition/ Unrated Version)/ Half Baked'),
 ('Babe (Dolby Digital)/ Babe: Pig In The City'),
 ('Liar Liar (Special Edition/ Dolby Digital)/ Ed-TV (Special Edition/ Dolby Digital)'),
 ('End Of Days/ Virus (Special Edition/ Dolby Digital)'),
 ('Erin Brockovich/ Primary Colors'),
 ('Playboy Playmates Bustin\' Out'),
 ('Deep Core'),
 ('Mommie Dearest'),
 ('Place In The Sun (Special Edition)'),
 ('Pledge'),
 ('Proof Of Life (Special Edition)'),
 ('Star Trek TV #27: The Ultimate Computer/ The Omega Glory'),
 ('Star Trek TV #28: Assignment Earth/ Spectre Of The Gun'),
 ('State And Main (Special Edition)'),
 ('Austin Blues #1: Song Xpress'),
 ('Bach: Organ Spectacular: Ton Koopman (DVD-Audio)'),
 ('Classic Blues #1: Song Xpress'),
 ('Classic Rock #3: Song Xpress'),
 ('Classic Surf #1: Song Xpress'),
 ('Dvorak: Symphony 9: From The New World: Harnoncourt (DVD-Audio)'),
 ('Fourplay: Fourplay (DVD-Audio)'),
 ('Luis Miguel: Romances (DVD-Audio)'),
 ('Missy \"Misdemeanor\" Elliott: Hits Of Miss E: The Videos #1'),
 ('Modern Rock #1: Song Xpress'),
 ('Party Tunes #1: Song Xpress'),
 ('Down To Earth'),
 ('Gift'),
 ('Wayne\'s World (Special Edition)'),
 ('Wayne\'s World 1 & 2: The Complete Epic (Special Edition)'),
 ('Wayne\'s World 2 (Special Edition)'),
 ('Any Given Sunday (Special Edition)'),
 ('Mishima: A Life In Four Chapters'),
 ('Sugar And Spice'),
 ('Thirteen Days (Special Edition)'),
 ('Get Carter: Special Edition'),
 ('Caveman\'s Valentine'),
 ('Family Man (Special Edition)'),
 ('Goonies (Special Edition)'),
 ('Head Over Heels'),
 ('Meet Joe Black: The Ultimate Edition (Special Edition)'),
 ('Notting Hill: The Ultimate Edition (Special Edition)'),
 ('Patch Adams: The Ultimate Edition (Special Edition)'),
 ('Scooby Doo\'s Spookiest Tales'),
 ('Playboy American Beauties: Sexy Girls Next Door'),
 ('T-Rex: Back To The Cretaceous: IMAX'),
 ('Hatari!'),
 ('Nightbreed'),
 ('Paint Your Wagon'),
 ('Shootist'),
 ('Audrey Rose'),
 ('Beast Within'),
 ('Blow Out'),
 ('Breeders'),
 ('Candyman 2: Farewell To The Flesh'),
 ('Carrie (Special Edition)'),
 ('Count Yorga, Vampire'),
 ('Crossfire Trail'),
 ('Dressed To Kill (Special Edition)'),
 ('Dunwich Horror'),
 ('First Power'),
 ('Haunted Honeymoon'),
 ('Howling'),
 ('Invaders From Mars (1986)'),
 ('Island Of Dr. Moreau (1977)'),
 ('It! The Terror From Beyond Space'),
 ('Killer Klowns From Outer Space (Special Edition)'),
 ('Mars Needs Women'),
 ('Monster That Challenged The World'),
 ('Planet Of The Vampires'),
 ('Reptilicus'),
 ('Scanners'),
 ('Sweet November'),
 ('Theatre Of Blood'),
 ('Valentine (Special Edition)'),
 ('Twice Told Tales'),
 ('Things You Can Tell Just By Looking At Her'),
 ('Gremlins'),
 ('John Waters Collection #1: Hairspray/ Pecker (Special Edition)'),
 ('Forrest Gump (Special Edition)'),
 ('Nuremberg'),
 ('Air Rage (Special Edition)'),
 ('Alice Cooper: Welcome To My Nightmare (DVD-Audio)'),
 ('Funeral In Berlin'),
 ('Hitters On Hitting: Finding The Sweet Spot: Major League Baseball'),
 ('Hunter'),
 ('Mahler: Symphony 3 In D Minor: Kent Nagano'),
 ('Star Trek TV #29: Elaan Of Troyius/ The Paradise Syndrome'),
 ('Star Trek TV #30: The Enterprise Incident/ And The Children Shall Lead'),
 ('Hannibal (Special Edition)'),
 ('Silence Of The Lambs (Special Edition/ Pan & Scan)'),
 ('Silence Of The Lambs (Special Edition/ Widescreen)'),
 ('Human Face'),
 ('Elizabeth R'),
 ('Fawlty Towers #1'),
 ('Fawlty Towers #2'),
 ('Fawlty Towers #3'),
 ('Fawlty Towers: The Complete Collection'),
 ('Robbie The Reindeer'),
 ('Teletubbies: Baby Animals'),
 ('Waiting For Guffman (Special Edition)'),
 ('Incredible Adventures Of Wallace And Gromit'),
 ('Abbott And Costello Meet The Mummy'),
 ('Classic Monsters: The Definitive Collection 3-Pack (Special Edition)'),
 ('Dracula\'s Daughter/ Son Of Dracula'),
 ('Frankenstein Meets The Wolf Man/ House Of Frankenstein'),
 ('Mummy\'s Ghost/ The Mummy\'s Curse'),
 ('Mummy\'s Hand/ The Mummy\'s Tomb'),
 ('Son Of Frankenstein/ Ghost Of Frankenstein'),
 ('Werewolf Of London/ She-Wolf Of London'),
 ('Tremors (Special Edition)/ Tremors 2: Aftershocks'),
 ('Underneath/ Village Of The Damned'),
 ('American Werewolf In London (Special Edition)'),
 ('Blood Simple'),
 ('Bride Of Chucky/ Child\'s Play 2: Chucky\'s Back'),
 ('Cape Fear (Special Edition/ 1962)'),
 ('Cape Fear (Special Edition/ 1991)'),
 ('Darkman/ Darkman 2: The Return Of Durant'),
 ('FlixMix: Boogeymen'),
 ('Halloween 2'),
 ('Play Misty For Me'),
 ('15 Minutes (Special Edition)'),
 ('3000 Miles To Graceland'),
 ('American Pie: The Ultimate Edition (R Rated Version/ Special Edition)'),
 ('American Pie: The Ultimate Edition (Unrated Version/ Special Edition)'),
 ('Enemy At The Gates'),
 ('House Party 4: Down To The Last Minute'),
 ('Never Ending Story'),
 ('Never Ending Story 2'),
 ('See Spot Run (Special Edition)'),
 ('Willy Wonka And The Chocolate Factory (Special Edition)'),
 ('Along Came Jones'),
 ('Eddie And The Cruisers'),
 ('French Lieutenant\'s Woman'),
 ('Home For The Holidays (Special Edition)'),
 ('How The Grinch Stole Christmas (Limited Special Edition/ 2000)'),
 ('How The Grinch Stole Christmas (Pan & Scan/ Special Edition/ 2000)'),
 ('How The Grinch Stole Christmas (Widescreen/ Special Edition/ 2000)'),
 ('Little Man Tate (Special Edition)'),
 ('Princess Bride (Special Edition)'),
 ('Return Of A Man Called Horse'),
 ('Under Fire'),
 ('Valdez Is Coming'),
 ('Woman In Red'),
 ('Chato\'s Land'),
 ('Comes A Horseman'),
 ('Godfather DVD Collection (Special Edition)'),
 ('Hole In The Head'),
 ('Irma La Douce'),
 ('It\'s A Mad Mad Mad Mad World (Special Edition)'),
 ('King Solomon\'s Mines'),
 ('Lawman'),
 ('Little Foxes'),
 ('Pocketful Of Miracles'),
 ('Quigley Down Under'),
 ('Sayonara'),
 ('Josie And The Pussycats (Special Edition)'),
 ('CItizen Kane'),
 ('Terminator'),
 ('Fiddler on the Roof (Special Edition)'),
 ('Blow (Special Edition)'),
 ('Company Man'),
 ('Daybreak (Special Edition)'),
 ('Marathon Man'),
 ('Star Trek TV #31: Spock\'s Brain/ Is There In Truth No Beauty?'),
 ('Star Trek TV #32: The Empath/ The Tholian Web'),
 ('Dish'),
 ('Driven (Special Edition)'),
 ('Exit Wounds'),
 ('Pokemon 3: The Movie'),
 ('A.I.: Artificial Intelligence: The Soundtrack (DVD-Audio)'),
 ('Missy \"Misdemeanor\" Elliott: Miss E: So Addictive (DVD-Audio)'),
 ('Philip Glass: Koyaanisqatsi (DVD-Audio)'),
 ('Mummy Returns (Special Edition/ Pan & Scan)'),
 ('Mummy Returns (Special Edition/ Widescreen)'),
 ('A*Teens: Bouncing Off The Ceiling/ Mamma Mia DVD Single'),
 ('Arabella: Strauss: Metropolitan Opera'),
 ('BBMak: Sooner And Later: Our First Year In America'),
 ('Blink 182: Man Overboard/ Adam\'s Song DVD Single'),
 ('Caetano Veloso: Prenda Minha'),
 ('Carmen: Bizet: James Levine: Metropolitan Opera'),
 ('Der Rosenkavalier: Strauss: Carlos Kleiber: Vienna Opera'),
 ('Die Fledermaus: Strauss: Carlos Kleiber: Bavarian State Opera'),
 ('Die Walkure: Wagner: James Levine: Metropolitan Opera'),
 ('Die Zauberflote: Mozart: James Levine: Metropolitan Opera'),
 ('Eminem: E'),
 ('Essential Ballet'),
 ('Fires Of Kuwait: IMAX'),
 ('Frank Lloyd Wright'),
 ('Freddie Mercury: The Video Collection'),
 ('Giselle: American Ballet Theatre'),
 ('Hanson: At The Fillmore'),
 ('Il Trovatore: Verdi: James Levine: Metropolitan Opera'),
 ('Insane Clown Posse: Big Money Hustla$'),
 ('Jay-Z: The Making Of Guilty Until Proven Innocent DVD Single'),
 ('Lewis And Clark: The Journey Of The Corps Of Discovery (Special Edition)'),
 ('Thomas Jefferson'),
 ('K-Ci And Jojo: All My Life/ Wanna Do You Right DVD Single'),
 ('La Traviata: Verdi: Georg Solti: Royal Opera'),
 ('Motley Crue: Lewd, Crued And Tattooed'),
 ('Nutcracker: Tchaikovsky: Kirov Ballet'),
 ('Otello: Verdi: Herbert Von Karajan'),
 ('Patti Labelle: Live! One Night Only'),
 ('Rammstein: Live Aus Berlin'),
 ('Rigoletto: Verdi: Riccardo Chailly'),
 ('Santana: Sacred Fire: Live In Mexico'),
 ('Doctor Who: Spearhead From Space (Special Edition)'),
 ('Doctor Who: The Five Doctors (Special Edition)'),
 ('Survivor: Australian Outback: Season #2: Greatest And Most Outrageous Moments'),
 ('Charlotte\'s Web (Pan & Scan)'),
 ('Crocodile Dundee'),
 ('Hobbit'),
 ('Let It Ride'),
 ('Lord Of The Rings'),
 ('Mission Impossible/ Mission Impossible 2'),
 ('National Geographic: Africa'),
 ('Rugrats Movie/ Rugrats In Paris: The Movie'),
 ('Aida: Verdi: James Levine: Metropolitan Opera'),
 ('Andrea Bocelli: Sacred Arias'),
 ('Anne-Sophie Mutter: A Life With Beethoven'),
 ('Blink 182: The Urethra Chronicles'),
 ('Crocodile Dundee In Los Angeles'),
 ('Crocodile Dundee 2'),
 ('Into The Arms Of Strangers: Stories Of The Kindertransport (Special Edition)'),
 ('Powerman 5000: Backstage And Beyond The Infinite'),
 ('Return Of The King'),
 ('Secret Garden: A Night With Secret Garden'),
 ('Miles Davis: Miles In Paris'),
 ('Twiztid: Born Twiztid'),
 ('Doctor Who: The Robots Of Death (Special Edition)'),
 ('Paul Simon: You\'re The One (DVD-Audio)'),
 ('Prancer'),
 ('Roboco'),
 ('When Worlds Collide'),
 ('Along Came a Spider'),
 ('Pet Sematary 2'),
 ('Tales From The Darkside: The Movie (Special Edition)'),
 ('Friday The 13th 5: A New Beginning'),
 ('Friday The 13th 6: Jason Lives'),
 ('Across 110th Street'),
 ('American Ninja'),
 ('Brannigan'),
 ('Bucktown'),
 ('Clambake'),
 ('Colors'),
 ('Cornbread, Earl And Me'),
 ('Craig David: Fill Me In DVD Single'),
 ('Destiny In Space: IMAX'),
 ('Five On The Black Hand Side'),
 ('Hail Columbia!: IMAX'),
 ('Heart Of Dixie'),
 ('Hell Up In Harlem'),
 ('IMAX Space Collection'),
 ('K.D. Lang: Live By Request'),
 ('MacArthur'),
 ('Making The Grade'),
 ('Masters Of The Universe'),
 ('Midway (Special Edition)'),
 ('Mission To Mir: IMAX'),
 ('Not Without My Daughter'),
 ('Running Scared'),
 ('Scooby Doo And The Cyber Chase'),
 ('She Devil'),
 ('Shiloh'),
 ('Shiloh 2: Shiloh Season'),
 ('Kansas'),
 ('Dress Code'),
 ('John Waters Collection #2: Polyester/ Desperate Living (Special Edition)'),
 ('Doctor Zhivago (Special Edition)'),
 ('John Waters Collection #3: Pink Flamingos/ Female Trouble (Special Edition)'),
 ('Beautiful Creatures'),
 ('Rat'),
 ('Stardom'),
 ('Tremors 3: Back To Perfection'),
 ('New York'),
 ('Empire Of The Sun'),
 ('Grandma Got Run Over By A Reindeer'),
 ('Mummy (1959)'),
 ('Bjork: Hidden Place DVD Single'),
 ('Land Before Time: The Big Freeze'),
 ('Angel Eyes (Special Edition/ 2001)'),
 ('He Said, She Said (Special Edition)'),
 ('Rugrats: Decade In Diapers'),
 ('Star Trek TV #35: That Which Survives/ Let That Be Your Last Battlefield'),
 ('Star Trek TV #36: Whom Gods Destroy/ The Mark Of Gideon'),
 ('Swordfish (Special Edition)'),
 ('Town And Country'),
 ('Andrew Lloyd Webber Spotlight Performance Box Set'),
 ('Andrew Lloyd Webber: Royal Albert Hall Celebration'),
 ('Butcher\'s Wife'),
 ('Michael Flatley: Feet Of Flames'),
 ('Powerpuff Girls: Meet The Beat Alls (Special Edition)'),
 ('Beethoven\'s 4th'),
 ('Cats: The Ultimate Edition'),
 ('Michael Flatley: Gold'),
 ('Boss Of Bosses'),
 ('Broadway Danny Rose'),
 ('Choose Me'),
 ('Dogs Of War'),
 ('Dominick And Eugene'),
 ('Gang Related'),
 ('Gregory\'s Girl'),
 ('Hannah And Her Sisters'),
 ('Midsummer Night\'s Sex Comedy'),
 ('Of Mice And Men (1992)'),
 ('Purple Rose Of Cairo'),
 ('Radio Days'),
 ('Woody Allen Collection 1982-1987'),
 ('Zelig'),
 ('Angry Red Planet'),
 ('At The Earth\'s Core'),
 ('Christina\'s House'),
 ('Empire Of The Ants'),
 ('Eye For An Eye (1981)'),
 ('I Bury The Living (MGM)'),
 ('Invasion U.S.A.'),
 ('Lone Wolf McQuade'),
 ('Lord Of The Flies (1990)'),
 ('Morons From Outer Space'),
 ('People That Time Forgot'),
 ('Strange Invaders'),
 ('War Gods Of The Deep'),
 ('Cats And Dogs (Special Edition)'),
 ('South Park: Timmy!'),
 ('Friends: The Best Of Friends #3'),
 ('Friends: The Best Of Friends #4'),
 ('Friends: The Best Of Friends Collection #1-4'),
 ('Friends: The Best Of Friends Gift Set #3 & 4'),
 ('South Park: Winter Wonderland'),
 ('Frankie And Johnny (1991)'),
 ('Star Trek: The Motion Pictures DVD Collection 1-9'),
 ('Star Trek: The Original Crew Movie Collection 1-6'),
 ('What\'s Eating Gilbert Grape'),
 ('MTV: Inside Fear'),
 ('MTV: The Real World You Never Saw: Back To New York'),
 ('Star Trek 1: The Motion Picture: The Director\'s Edition (Special Edition)'),
 ('Apocalypse Now Redux'),
 ('Bill And Ted\'s Bogus Journey'),
 ('Bill And Ted\'s Excellent Adventure'),
 ('Defiant Ones'),
 ('Dirty Rotten Scoundrels (Special Edition)'),
 ('Fritz The Cat'),
 ('Handmaid\'s Tale'),
 ('Inherit The Wind'),
 ('Lara Croft: Tomb Raider (Special Edition)'),
 ('Look Back In Anger'),
 ('Lover'),
 ('Nine Lives Of Fritz The Cat'),
 ('Party (1968)'),
 ('Pokemon: Mewtwo Returns'),
 ('Separate Tables (Special Edition)'),
 ('Topkapi'),
 ('Witness For The Prosecution'),
 ('Dodsworth'),
 ('Josie And The Pussycats (Special Edition/ PG Version)'),
 ('Gone with Sunny'),
 ('Matrix 2');